export const projects = [
  {
    title: 'GPT-3 APP',
    description: "I developed a sophisticated GPT-3 web application using React.js, CSS, and HTML. This project showcases my ability to integrate cutting-edge AI technology into a user-friendly web interface, demonstrating both my technical proficiency and my commitment to creating impactful digital solutions.",
    image: '/images/gpt-3.png ',
    tags: ['React', 'CSS', 'JavaScript'],
    visit: 'https://shamy-gpt-app.netlify.app/',
    source: 'https://github.com/shamyorjani/GPT3-react-app/tree/master',
    id: 0,
  },
  {
    title: 'EarningLance',
    description:"The EarningLance web application was successfully migrated from core PHP to the Laravel framework. This project demonstrates proficiency in modernizing legacy systems, and improving overall functionality. It involved a complete overhaul of the existing codebase, to boost security, performance, and scalability.",
    image: '/images/earningLance.jpeg',
    tags: ['Laravel', 'JavaScript', 'PHP'],
    source: 'https://github.com/shamyorjani/earninglance_laravel_updated',
    visit: 'https://github.com/shamyorjani/earninglance_laravel_updated',
    id: 1,
  },
  {
    title: 'Schooling System',
    description: "The Schooling System Dashboard is a comprehensive web application designed to streamline the management and operations of educational institutions. Developed using Laravel for the back-end and React.js for the front-end, this dashboard provides a user-friendly interface for administrators, teachers, and students.",
    image: '/images/schooling-system.jpeg',
    tags: ['Blade', 'Laravel', 'JavaScript', 'PHP'],
    source: 'https://github.com/shamyorjani/my-cms-script',
    visit: 'https://github.com/shamyorjani/my-cms-script',
    id: 2,
  },
  {
    title: 'Hair Dresser',
    description: "The Hairdresser Website Frontend is a sleek and modern web application designed to enhance the online presence of hair salons and provide an engaging user experience for clients. Developed using HTML, and CSS, this website offers a responsive and visually appealing interface.",
    image: '/images/heir-drasser.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/shamyorjani/Hairdresser-website',
    visit: 'https://hair-dresser-web.netlify.app/',
    id: 3,
  },
];
export const TimeLineData = [
  { year: 2020, text: 'Began web development journey', },
  { year: 2021, text: 'Focused on JavaScript and React.js', },
  { year: 2022, text: 'Learned Laravel and PHP for back-end development', },
  { year: 2023, text: 'Contributed to open-source projects', },
  { year: 2024, text: 'Founded own web development platform', },
];
